---
name: Pull Request Labeler

on: [pull_request] # yamllint disable-line rule:truthy

jobs:
  label:
    name: auto label
    runs-on: ubuntu-latest
    steps:
    - name: Generate a token
      id: generate_token
      uses: tibdex/github-app-token@v2
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.PRIVATE_KEY }}
    - uses: actions/labeler@v5
      continue-on-error: true
      with:
        repo-token: ${{ steps.generate_token.outputs.token }}
    - uses: TimonVS/pr-labeler-action@v5.0.0
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
